/* global describe, it, chai */

// https://mochajs.org/
// https://www.chaijs.com/

import seq from '../seq.mjs'
const expect = chai.expect

describe('seq function', () => {
  it('From integer', () => {
    const ite = seq(3)
    expect(ite).to.be.an('object')
    expect(ite[Symbol.iterator]).to.be.a('function')
    expect(Array.from(ite)).to.deep.equal([0, 1, 2])
  })
  it('From iterator', () => {
    const ite = seq([10, 20, 30])
    expect(ite).to.be.an('object')
    expect(ite[Symbol.iterator]).to.be.a('function')
    expect(Array.from(ite)).to.deep.equal([10, 20, 30])
  })
  it('Errors', () => {
    expect(() => { seq(false) }).throw(Error)
  })
})

describe('ArrayIterator methods', () => {
  const ArrayIterator = seq(3).constructor
  it('concat', () => {
    const ite = seq(0).concat(0)
    const res11 = Array.from(seq([10]).concat([20, 30], 40))
    const res12 = [10].concat([20, 30], 40)
    expect(ite).to.be.an.instanceof(ArrayIterator)
    expect(res11).to.deep.equal(res12)
  })
  it('entries', () => {
    const ite = seq(0).entries()
    const res11 = Array.from(seq([10, 20, 30]).entries())
    const res12 = Array.from([10, 20, 30].entries())
    expect(ite).to.be.an.instanceof(ArrayIterator)
    expect(res11).to.deep.equal(res12)
  })
  it('every', () => {
    const res11 = seq(4).every(v => v >= 0)
    const res12 = [0, 1, 2, 3].every(v => v >= 0)
    const res21 = seq(4).every(v => v !== 2)
    const res22 = [0, 1, 2, 3].every(v => v !== 2)
    const res31 = seq(4).every(v => null)
    const res32 = [0, 1, 2, 3].every(v => null)
    const res41 = seq(4).every(function (v, i) { return v === i && this.p }, { p: true })
    const res42 = [0, 1, 2, 3].every(function (v, i) { return v === i && this.p }, { p: true })
    expect(res11).to.equal(res12)
    expect(res21).to.equal(res22)
    expect(res31).to.equal(res32)
    expect(res41).to.equal(res42)
  })
  it('fill', () => {
    const ite = seq(0).fill(0)
    const res11 = Array.from(seq(5).fill(9, 1, 3))
    const res12 = [0, 1, 2, 3, 4].fill(9, 1, 3)
    const res21 = Array.from(seq(5).fill(9, -4, -1))
    const res22 = [0, 1, 2, 3, 4].fill(9, -4, -1)
    expect(ite).to.be.an.instanceof(ArrayIterator)
    expect(res11).to.deep.equal(res12)
    expect(res21).to.deep.equal(res22)
  })
  it('filter', () => {
    const ite = seq(0).filter(v => true)
    const res11 = Array.from(seq(5).filter(v => v % 2 === 0))
    const res12 = [0, 1, 2, 3, 4].filter(v => v % 2 === 0)
    const res21 = Array.from(seq(5).filter(function (v, i) { return (v + i) % 6 === this.p }, { p: 2 }))
    const res22 = [0, 1, 2, 3, 4].filter(function (v, i) { return (v + i) % 6 === this.p }, { p: 2 })
    expect(ite).to.be.an.instanceof(ArrayIterator)
    expect(res11).to.deep.equal(res12)
    expect(res21).to.deep.equal(res22)
  })
  it('find', () => {
    const res11 = seq(4).find(v => v === 2)
    const res12 = [0, 1, 2, 3].find(v => v === 2)
    const res21 = seq(4).find(v => v === 9)
    const res22 = [0, 1, 2, 3].find(v => v === 9)
    const res31 = seq(4).find(function (v, i) { return v + i === this.p }, { p: 4 })
    const res32 = [0, 1, 2, 3].find(function (v, i) { return v + i === this.p }, { p: 4 })
    expect(res11).to.equal(res12)
    expect(res21).to.equal(res22)
    expect(res31).to.equal(res32)
  })
  it('findIndex', () => {
    const res11 = seq(4).findIndex(v => v === 2)
    const res12 = [0, 1, 2, 3].findIndex(v => v === 2)
    const res21 = seq(4).findIndex(v => v === 9)
    const res22 = [0, 1, 2, 3].findIndex(v => v === 9)
    const res31 = seq(4).findIndex(function (v, i) { return (v + i) === this.p }, { p: 4 })
    const res32 = [0, 1, 2, 3].findIndex(function (v, i) { return (v + i) === this.p }, { p: 4 })
    expect(res11).to.equal(res12)
    expect(res21).to.equal(res22)
    expect(res31).to.equal(res32)
  })
  it('flat', () => {
    const ite = seq(0).flat()
    const res11 = Array.from(seq([10, [20, [30]], 40]).flat())
    const res12 = [10, [20, [30]], 40].flat()
    const res21 = Array.from(seq([10, [20, [30]], 40]).flat(2))
    const res22 = [10, [20, [30]], 40].flat(2)
    const res31 = Array.from(seq([null]).flat())
    const res32 = [null].flat()
    expect(ite).to.be.an.instanceof(ArrayIterator)
    expect(res11).to.deep.equal(res12)
    expect(res21).to.deep.equal(res22)
    expect(res31).to.deep.equal(res32)
  })
  it('flatMap', () => {
    const ite = seq(0).flatMap()
    const res11 = Array.from(seq(5).flatMap(v => v % 3 === 0 ? [] : [v, v * 3]))
    const res12 = [0, 1, 2, 3, 4].flatMap(v => v % 3 === 0 ? [] : [v, v * 3])
    const res21 = Array.from(seq(5).flatMap(function (v, i) { return v % this.p === 1 ? [] : [v, v * i] }, { p: 2 }))
    const res22 = [0, 1, 2, 3, 4].flatMap(function (v, i) { return v % this.p === 1 ? [] : [v, v * i] }, { p: 2 })
    expect(ite).to.be.an.instanceof(ArrayIterator)
    expect(res11).to.deep.equal(res12)
    expect(res21).to.deep.equal(res22)
  })
  it('forEach', () => {
    const vals = []
    seq(2).forEach(v => vals.push(v))
    expect(vals).to.deep.equal([0, 1])
  })
  it('includes', () => {
    const res11 = seq(4).includes(1)
    const res12 = [0, 1, 2, 3].includes(1)
    const res21 = seq(4).includes(1, 1)
    const res22 = [0, 1, 2, 3].includes(1, 1)
    const res31 = seq(4).includes(1, 2)
    const res32 = [0, 1, 2, 3].includes(1, 2)
    expect(res11).to.equal(res12)
    expect(res21).to.equal(res22)
    expect(res31).to.equal(res32)
  })
  it('indexOf', () => {
    const res11 = seq([1, 0, 1, 2, 3]).indexOf(1)
    const res12 = [1, 0, 1, 2, 3].indexOf(1)
    const res21 = seq([1, 0, 1, 2, 3]).indexOf(1, 2)
    const res22 = [1, 0, 1, 2, 3].indexOf(1, 2)
    const res31 = seq([1, 0, 1, 2, 3]).indexOf(1, 3)
    const res32 = [1, 0, 1, 2, 3].indexOf(1, 3)
    const res41 = seq([1, 0, 1, 2, 3]).indexOf(1, -1)
    const res42 = [1, 0, 1, 2, 3].indexOf(1, -1)
    expect(res11).to.equal(res12)
    expect(res21).to.equal(res22)
    expect(res31).to.equal(res32)
    expect(res41).to.equal(res42)
  })
  it('join', () => {
    const res11 = seq(2).join()
    const res12 = [0, 1].join()
    const res21 = seq(2).join(';')
    const res22 = [0, 1].join(';')
    expect(res11).to.equal(res12)
    expect(res21).to.equal(res22)
  })
  it('keys', () => {
    const ite = seq(0).keys()
    const res11 = Array.from(seq([10, 20, 30]).keys())
    const res12 = Array.from([10, 20, 30].keys())
    expect(ite).to.be.an.instanceof(ArrayIterator)
    expect(res11).to.deep.equal(res12)
  })
  it('lastIndexOf', () => {
    const res11 = seq([1, 0, 1, 2, 3]).lastIndexOf(1)
    const res12 = [1, 0, 1, 2, 3].lastIndexOf(1)
    const res21 = seq([1, 0, 1, 2, 3]).lastIndexOf(1, 1)
    const res22 = [1, 0, 1, 2, 3].lastIndexOf(1, 1)
    const res31 = seq([1, 0, 1, 2, 3]).lastIndexOf(1, 2)
    const res32 = [1, 0, 1, 2, 3].lastIndexOf(1, 2)
    const res41 = seq([1, 0, 1, 2, 3]).lastIndexOf(1, -1)
    const res42 = [1, 0, 1, 2, 3].lastIndexOf(1, -1)
    expect(res11).to.equal(res12)
    expect(res21).to.equal(res22)
    expect(res31).to.equal(res32)
    expect(res41).to.equal(res42)
  })
  it('map', () => {
    const ite = seq(0).map(v => true)
    const res11 = Array.from(seq(5).map(v => v * 2 + 1))
    const res12 = [0, 1, 2, 3, 4].map(v => v * 2 + 1)
    const res21 = Array.from(seq(5).map(function (v, i) { return (v + i) + this.p }, { p: 3 }))
    const res22 = [0, 1, 2, 3, 4].map(function (v, i) { return (v + i) + this.p }, { p: 3 })
    expect(ite).to.be.an.instanceof(ArrayIterator)
    expect(res11).to.deep.equal(res12)
    expect(res21).to.deep.equal(res22)
  })
  it('reduce', () => {
    const res11 = seq(5).reduce((l, r) => l + r)
    const res12 = [0, 1, 2, 3, 4].reduce((l, r) => l + r)
    const res21 = seq(5).reduce((l, r) => l + r, 100)
    const res22 = [0, 1, 2, 3, 4].reduce((l, r) => l + r, 100)
    const res31 = seq([[0, 1], [2, 3]]).reduce((l, r) => l.concat(r))
    const res32 = [[0, 1], [2, 3]].reduce((l, r) => l.concat(r))
    expect(res11).to.equal(res12)
    expect(res21).to.equal(res22)
    expect(res31).to.deep.equal(res32)
  })
  it('reduceRight', () => {
    const res11 = seq(5).reduceRight((l, r) => l + r)
    const res12 = [0, 1, 2, 3, 4].reduceRight((l, r) => l + r)
    const res21 = seq(5).reduceRight((l, r) => l + r, 100)
    const res22 = [0, 1, 2, 3, 4].reduceRight((l, r) => l + r, 100)
    const res31 = seq([[0, 1], [2, 3]]).reduceRight((l, r) => l.concat(r))
    const res32 = [[0, 1], [2, 3]].reduceRight((l, r) => l.concat(r))
    expect(res11).to.equal(res12)
    expect(res21).to.equal(res22)
    expect(res31).to.deep.equal(res32)
  })
  it('slice', () => {
    const ite = seq(0).slice()
    const res11 = Array.from(seq(5).slice(1, 3))
    const res12 = [0, 1, 2, 3, 4].slice(1, 3)
    const res21 = Array.from(seq(5).slice(1))
    const res22 = [0, 1, 2, 3, 4].slice(1)
    const res31 = Array.from(seq(5).slice())
    const res32 = [0, 1, 2, 3, 4].slice()
    const res41 = Array.from(seq(5).slice(-1))
    const res42 = [0, 1, 2, 3, 4].slice(-1)
    expect(ite).to.be.an.instanceof(ArrayIterator)
    expect(res11).to.deep.equal(res12)
    expect(res21).to.deep.equal(res22)
    expect(res31).to.deep.equal(res32)
    expect(res41).to.deep.equal(res42)
  })
  it('some', () => {
    const res11 = seq(4).some(v => v >= 0)
    const res12 = [0, 1, 2, 3].some(v => v >= 0)
    const res21 = seq(4).some(v => v !== 2)
    const res22 = [0, 1, 2, 3].some(v => v !== 2)
    const res31 = seq(4).some(v => null)
    const res32 = [0, 1, 2, 3].some(v => null)
    const res41 = seq(4).some(function (v, i) { return v === i && this.p }, { p: true })
    const res42 = [0, 1, 2, 3].some(function (v, i) { return v === i && this.p }, { p: true })
    expect(res11).to.equal(res12)
    expect(res21).to.equal(res22)
    expect(res31).to.equal(res32)
    expect(res41).to.equal(res42)
  })
  it('toArray', () => {
    const res11 = seq(4).toArray()
    const res12 = Array.from(seq(4))
    expect(res11).to.deep.equal(res12)
  })
  it('toString', () => {
    const res11 = seq(2).toString()
    expect(res11).to.equal('01')
  })
  it('values', () => {
    const ite = seq(0).values()
    const res11 = Array.from(seq([10, 20, 30]).values())
    const res12 = Array.from([10, 20, 30].values())
    expect(ite).to.be.an.instanceof(ArrayIterator)
    expect(res11).to.deep.equal(res12)
  })
})
describe('Processing orders', () => {
  it('Basic', () => {
    const orders = []
    seq(2).map(v => {
      orders.push('#1', v)
      return v
    }).map(v => {
      orders.push('#2', v)
      return v
    }).join()
    expect(orders).to.deep.equal(['#1', 0, '#2', 0, '#1', 1, '#2', 1])
  })
  it('Immediate termination', () => {
    const orders = []
    seq(4).map(v => {
      orders.push('#1', v)
      return v
    }).findIndex(v => {
      orders.push('#2', v)
      return v === 1
    })
    expect(orders).to.deep.equal(['#1', 0, '#2', 0, '#1', 1, '#2', 1])
  })
})
